name: test

on:
  pull_request:
  workflow_dispatch:

jobs:
  test-and-build:
    name: "test and build"
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v6
      - name: setup rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: setup just
        uses: extractions/setup-just@v3
      - name: test
        run: just test
      - name: build
        run: just build
